### ISSUE TITLE
Starship doesn't take off (combined with Starship Expansion Project mod)

### ISSUE THREAD

**Issue by vicen0015** [PEKKA-Space/PEKKAsMods#1]
So, I tried to use PEKKA's OLM and OLIT and attach them into SEP's Starship just to see how it would work, but when I separate stages and light up the engines the vehicle does not liftoff, and it's not a rooting issue, the root is Starship, so I can't find how to solve this issue 
![Screenshot_29](https://github.com/PEKKA-Space/PEKKAsMods/assets/134088986/4cc9eaac-3b57-417e-9c16-0d96e929c9dd)
![Screenshot_30](https://github.com/PEKKA-Space/PEKKAsMods/assets/134088986/588c62c0-449b-4f31-b4d5-0339a8afb036)

**Comment by vicen0015** [comment]
Is this a compatibility issue? Can it be solved?

**Comment by PEKKA-Space** [comment]
I dont know why it doesnt work, you should use my Starship in conmbination with my Launch Tower for it to work as intended.
