### ISSUE TITLE
Where is the Stock configs?

### ISSUE THREAD

**Issue by heyseb4** [PEKKA-Space/PEKKAsMods#2]
I believe I have the RO version of the mod, but where are the Stock configs for the Ship and Booster?

**Comment by PEKKA-Space** [comment]
Every version of the Mod contains the Stock Configs in the Folder PEKKAsMods -> Parts -> Starship. If you don't the JNSQ or RO Configs you can also delete them by delteing the folder ROconfigs and/or JNSQconfigs in the PEKKAsMods folder.

Hope that helps.

**Comment by heyseb4** [comment]
Thanks! I got the ship and booster to work now, but I have a new problem. I'm trying to use the KK static but when I hit Ctrl+K, it doesn't open the menu. The logs say it's because something is trying to reference Earth, but there's no Earth (since I am using Stock). How do I fix this?

**Comment by PEKKA-Space** [comment]
Sadly you don't. Either you play in RSS and it will work or you keep playing Stock where it won't work.
