### ISSUE TITLE
why is the kOS script not working

### ISSUE THREAD

**Issue by FuzzyLawsuit** [PEKKA-Space/PEKKAsMods#3]
![bild_2024-04-07_160251074](https://github.com/PEKKA-Space/PEKKAsMods/assets/166309561/8c603dcf-4790-47a4-9dd9-07c291fb60cc)

**Comment by PEKKA-Space** [comment]
You should open the script in notepad or another text editor. Then copy everything from there and in kOS just type: edit scriptname. then paste the copied script and save. At the end just type: run scriptname. and it should work. Hope this helps.

**Comment by FuzzyLawsuit** [comment]
![bild_2024-04-08_152502225](https://github.com/PEKKA-Space/PEKKAsMods/assets/166309561/4714b2c0-9f56-41f7-888a-06a1afd26e25)
still won't work

**Comment by PEKKA-Space** [comment]
The 1:/ should have been left out of your command then it should work. And if it doesn't try: switch to 0.

**Comment by FuzzyLawsuit** [comment]
![bild_2024-04-08_163509974](https://github.com/PEKKA-Space/PEKKAsMods/assets/166309561/bffd61e9-08e5-433a-8821-1dcffc27631f)
why won't it work even after writing switch to 0. and then run starship?

**Comment by PEKKA-Space** [comment]
You still have to create the file starship. So after writing: switch to 0. you should edit the file and then run it.

**Comment by FuzzyLawsuit** [comment]
it seems to be working now since I got a countdown on my screen
