### ISSUE TITLE
why are the engines on the upper stage starting at the same time as the first stage engines in the starship kOS script during lift off

### ISSUE THREAD

**Issue by FuzzyLawsuit** [PEKKA-Space/PEKKAsMods#4]

**Comment by PEKKA-Space** [comment]
Make sure you are using the craftfile provided by the mod which is under GameData/PEKKAsMods/Craftfiles/Starship-PEKKA.craft and put inside the folder Kerbal Space Program/Ships/VAB.

**Comment by FuzzyLawsuit** [comment]
okay now it works
