### ISSUE TITLE
Parts aren't showing up

### ISSUE THREAD

**Issue by Ferristik** [PEKKA-Space/PEKKAsMods#6]
I installed the mod and launched my game but the parts don't show up in the VAB and the ships wont load since there are no parts, also weirdly the mod doesn't show up on Janitor's Closet. how do i fix this?

**Comment by Ferristik** [comment]
here is KSP.log and ModuleManager.ConfigCache

https://www.mediafire.com/file/m9t7gm1bvnlhu0w/KSP.log/file
https://www.mediafire.com/file/tn3ungrij62l5fs/ModuleManager.ConfigCache.txt/file

**Comment by PEKKA-Space** [comment]
Janitors closet should show my parts as GameData i think (i know it's weird but i don't know how to fix it). I would be surpized if all my parts aren't there since ksp loads them just fine although the craft flies don't open which suggest that maybe one of the Rp-0/Ro mods is deleting or renaming them. If you search for "Pekka" will it show no parts?

**Comment by Ferristik** [comment]
![Screenshot_1](https://github.com/PEKKA-Space/PEKKAsMods/assets/143970003/e1abe6b1-6cdc-42db-b485-d7400f73b4c0)

**Comment by Ferristik** [comment]
![resim](https://github.com/PEKKA-Space/PEKKAsMods/assets/143970003/fb3c8b63-721a-44d5-ae58-83205519727f)
![resim](https://github.com/PEKKA-Space/PEKKAsMods/assets/143970003/647bebc4-9323-4039-900b-f3c202b893a8)

**Comment by PEKKA-Space** [comment]
Yeah that is weird.
Could you try to use it in a bare RO install without all the other mods?

**Comment by Ferristik** [comment]
okay i think i found it out mate

**Comment by Ferristik** [comment]
![resim](https://github.com/PEKKA-Space/PEKKAsMods/assets/143970003/17f7ce29-b94f-48d4-9f31-05a69680f35e)

it applies a delete because it doesn't have an rp-1 config, can you maybe fix this with module manager?

**Comment by Ferristik** [comment]
or tell me how i can exclude the parts from getting deleted

**Comment by Ferristik** [comment]
[NonRP0.txt](https://github.com/user-attachments/files/15916351/NonRP0.txt)
also here is the MM config that deletes non rp-0 parts so you could work with this i guess.

**Comment by PEKKA-Space** [comment]
Since this mod is not really designed for use in a career it's probably fine that the parts get deleted.

**Comment by Ferristik** [comment]
yeah but im using it for sandbox :(

**Comment by PEKKA-Space** [comment]
Then why don't you delete Rp-1?

**Comment by Ferristik** [comment]
> Then why don't you delete Rp-1?

because it has avionics and it's better to use them

**Comment by Ferristik** [comment]
so how do i exclude them

**Comment by PEKKA-Space** [comment]
if you have an express install folder in your gamedata then you could try deleting it.

**Comment by Ferristik** [comment]
okay it worked, can i ask what "Toggle Gimbal out" means?

**Comment by Ferristik** [comment]
nvm i found it out
